.TH COMPAK 1 "May 2026" "compak 1.0" "User Commands"

.SH NAME
compak \- minimal source-based package manager

.SH SYNOPSIS
.B compak
.RI < options >

.SH DESCRIPTION
.B compak
is a minimal source-based package manager which compiles the program at install time

.SH OPTIONS
.TP
.BR --help ", " -?
Show this help message

.TP
.BR --install ", " -i " " <package>
Install the specified package

.TP
.BR --remove ", " -r " " <package>
Uninstall the specified package

.TP
.BR --list ", " -l
List installed packages

.SH AUTHOR
GamerZero9512
