.TH COMPAK 1 "June 2026" "compak" "User Commands"

.SH NAME
compak - minimal source-based package manager

.SH SYNOPSIS
.B compak
.RI < options >

.SH DESCRIPTION
.B compak
is a minimal source-based package manager which compiles the package from source at install time

.SH OPTIONS
.TP
.BR --help ", " -?
Show this help message

.TP
.BR --install ", " -i " " <package>
Install the specified package

.TP
.BR --remove ", " -r " " <package>
Uninstall the specified package

.TP
.BR --list ", " -l
List installed packages

.TP
.BR --update ", " -u " " <package>
Update the specified package

.TP
.BR --update-all
Update all installed packages

.TP
.BR --clean
Remove compak temporary files

.TP
.BR --package ", " -p " " <folder>
Pack folder into compak-ready archive

.TP
.BR --view ", " -v " " <package>
View info about a package

.RS
.TP
.BR --raw
View the raw package manifest

.TP
.BR --simple
View a simple overview of the package
.RE

.SH AUTHOR
GamerZero9512
